# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Timothy M Beissinger
tagline:          Info
url:              http://timbeissinger.github.io
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
