title: "Timothy M Beissinger"
author: 
description: "Really cool blog about ... something"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://timbeissinger.github.io"
baseurl: 

comments:
    disqus: "niklasbuschmann"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/timbeissinger/"
  - twitter: "https://twitter.com/timbeissinger/"
  - google scholar: "https://scholar.google.com/citations?user=PHAEOXIAAAAJ&hl=en"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
