# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Timothy M Beissinger
tagline:          
url:              http://timbeissinger.github.io
paginate:         1
baseurl:          /
author:
  name:           Tim Beissinger
  url:            https://twitter.com/timbeissinger
  email:          timbeissinger@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/timbeissinger.io
